### ISSUE TITLE
Implement a build-time cache structure

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#107]
Some sites may choose to implement data processing inside templates/macros out of convenience and to keep site-building isolated to Grow. It's pretty common to, for example, leverage `g.csv` and do some data processing on the rows of one or more CSV files.

Unfortunately, the data-processing is performed on a per-page basis and there is no concept of caching across page renders. It may only be necessary to process data once per build. We can create a build-time cache allowing developers to cache processed data during the build to avoid re-processing it on each page render – if the same data is processed and used multiple times throughout the site.

@meizon – this should actually speed up our build a lot, since most of the build time is spent processing data from CSV files.

**Comment by meizon** [comment]
Sounds good to me. Something like memoize?

**Comment by jeremydw** [comment]
Today I did prototype with a `{{cache}}` function inside templates and it didn't seem to help building our site much. I thought looping over the CSVs and data files was the root cause of the slowdown, but it could be something else. While I think a cache tag (for either data structures or generated HTML) would be useful, I'm also going to look into seeing if the slowdown is the result of something else.

**Comment by jeremydw** [comment]
cce1e38 implements caching by default at build time for all tags, requiring no changes from the developer. This drastically speeds up builds (taking a benchmark site at 3.5 minutes for a build of 3500 files down to 30 seconds). So I'm going to close this issue for now since this new caching layer does most of the job.

20 of those seconds are spent installing and uninstalling translations, so it's possible we can cut the build time down further.

**Comment by jeremydw** [comment]
Benchmarks in case we implement optimizations related to translations/gettext:

With translations:
`Building: 3525/3525 (in 0:00:36)`

Without translations:
`Building: 3525/3525 (in 0:00:15)`
