### ISSUE TITLE
Investigate using $locale to override the default locale's yaml

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#114]
Currently, it's impossible to override the default locale's yaml using the `$locale` identifier. For example, if a pod's default locale is `en_US` and if you'd like to:

1. override specific content for `en_US`,
1. preserve `en_US` as the default locale,
1. and use the built-in `$locale` identifier to override just `en_US`,

... there is no way to do that other than to change a document's default locale to something else, update the paths for the new default locale, and copy the overridden data to a new yaml section with `$locale: en_US`. This is an OK workaround, but it's a bit roundabout.

The reason you cannot override a default locale's yaml currently is because the first section (the default locale's section) is *already* considered by the system to have an implicit `$locale: en_US` (when `en_US` is the default locale), so adding a new section with `$locale: en_US` would be equivalent to duplicating documents for `$locale: en_US` which is not supported.

Internally, this makes sense, but at the same time we should investigate whether it makes sense to revisit this and determine if we need a way to easily support the scenario mentioned in the bullet points above – or whether it's OK as-is.

@meizon FYI

**Comment by meizon** [comment]
Thanks for logging this. Having the ability to specify another en_US block would allow US specific content without having to override that in every subsequent locale block.

**Comment by WillsB3** [comment]
:+1: for this functionality.

**Comment by jeremydw** [comment]
Okay, closing this out as it's landed in 0.0.56.
