### ISSUE TITLE
Locale identifier mapping for importing translations

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#118]
To avoid manually managing files upon importing translations, we need a way for projects to specify the format of an external locale to an internal/CLDR locale. For example, localization request systems may spit out a locale such as "de" but internally a project may use "de_DE". We need a way to persist this mapping.

The structure of the mapping should be:

```
<external locale>:
- <internal locale>
- <internal locale>
- <internal locale>
```

This configuration should be in `localization` in podspec.yaml, but I'm not yet sure what it should be called. Maybe `imports` (since it's already under `localization`) or `import_identifiers`?

@meizon

**Comment by meizon** [comment]
Sounds great. Maybe `import_mapping` or `imports` like you suggest. I guess anything is fine as long as it sounds like it's connected to what you're doing when importing.
