### ISSUE TITLE
Auto-update from 0.0.54 -> 0.0.55 fails

### ISSUE THREAD

**Issue by WillsB3** [grow/pygrow#119]
Not sure if it's just me:

```
  Please update to the newest version of the Grow SDK.
  See release notes: https://github.com/grow/pygrow/releases/tag/0.0.55
  Your version: 0.0.54, latest version: 0.0.55
Auto update now? [y/N]: y
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
```

I was able to work around the issue by just running the install script again.

**Comment by jeremydw** [comment]
Someone reported this error before – but as it turns out that error isn't being caused by anything in Grow's code. I don't know if we can fix it, but we can certainly display a better error message with instructions to the user to shut down Grow and reinstall manually.

**Comment by WillsB3** [comment]
Cool - A better error sounds fine. Up until this point the auto-upgrade had been working great :+1:

**Comment by WillsB3** [comment]
FYI - Just seen this again:

<img width="813" alt="screen shot 2016-06-27 at 23 08 21" src="https://cloud.githubusercontent.com/assets/868834/16397420/4df0ee42-3cbc-11e6-8f6f-2b3f53581b11.png">

**Comment by jeremydw** [comment]
Yeah, not sure if this is fixable by Grow, unfortunately. It happens depending on your Python environment. In the latest version of Grow I just released, we show instructions on how to update manually with the update command.

https://github.com/grow/grow/issues/240
