### ISSUE TITLE
Grow update check is failing

### ISSUE THREAD

**Issue by anonymousandrew** [grow/pygrow#135]
$ gulp & grow run
[1] 5507
               Pod: <REDACTED>
           Address: http://localhost:8080/
      Server ready. Press ctrl-c to quit.
Cannot check for updates to the SDK while offline.
[14:31:09] Using gulpfile ~/<REDACTED>/gulpfile.js
[14:31:09] Starting 'build_js'...

I'm online but the check for whether or not I'm online is failing.

**Comment by jeremydw** [comment]
I can't repro this. :\ Any other debugging information you can provide?

**Comment by anonymousandrew** [comment]
It happens intermittently. I thought it was you, now I think it's me!
