### ISSUE TITLE
Error message has the wrong context

### ISSUE THREAD

**Issue by anonymousandrew** [grow/pygrow#146]
`$ grow deploy --auth=MYUSER@DOMAIN.com DESTINATION`
`Error: --auth must be specified before "build", e.g.: grow --auth=user@example.com build`

It seems like it didn't notice I was using deploy instead of build.

**Comment by jeremydw** [comment]
Yep, `--auth` moved to a global flag in 0.0.56 so we raise this error now. I've updated the deprecation notice to show the correct subcommand (deploy).
