### ISSUE TITLE
Submit Grow to StaticGen 

### ISSUE THREAD

**Issue by WillsB3** [grow/pygrow#151]
Just found [StaticGen](https://www.staticgen.com/) via this [Smashing Magazine article](http://www.smashingmagazine.com/2015/11/modern-static-website-generators-next-big-thing/). 

Should we submit Grow?

**Comment by jeremydw** [comment]
Yes, I think that'd be nice! :) I can get to this mid-week but if you have some spare cycles feel free to submit it yourself. This will be a nice submission to go along with the 1.0.0 release, which is imminent.

**Comment by WillsB3** [comment]
Here :) 

https://github.com/netlify/staticgen/pull/129

**Comment by WillsB3** [comment]
My PR has been accepted and Grow is now on StaticGen :)

http://www.staticgen.com/
