### ISSUE TITLE
Extra newline character when extracting strings that use multiline syntax

### ISSUE THREAD

**Issue by WillsB3** [grow/pygrow#170]
Say I have this in a content `.yaml` file:

```YAML
multiline@: >
  This is a multiline
  YAML string.
```

When extracting translations, the generated .po contains an extra newline character at the end of the string, like so:

```
#: /content/pages/home.yaml:0
msgid "This is a multiline YAML string.\n"
msgstr ""
```

There is no space character after the last character on the last line of the multiline string. I have a hunch that this behaviour has a reasonable explanation (perhaps a newline character in the source after a multiline string gets treated as whitespace so the parser treats it as such and adds \n). Having said that, it's a little annoying.

Is there any situation where the current behaviour would likely be the intended behaviour? If not does it make sense to/could we strip this extra newline at the end of the string as part of the translation export process?

**Comment by jeremydw** [comment]
Dug into this a little and I think this behavior is actually correct. I don't think Grow should transform the YAML content in any magical/non-obvious way that differs from an existing spec.

See this awesome answer on StackOverflow all about YAML and multi-line blocks: http://stackoverflow.com/a/21699210

If you use the block chomping character, I think you'll get the results you want, check it out below. If you agree, let's close out this issue. Thanks though, I learned a bunch about YAML today. ;P

```
>>> yaml.load('multiline: |\n    foo bar baz\n')
{'multiline': 'foo bar baz\n'}
>>> yaml.load('multiline: |-\n    foo bar baz\n')
{'multiline': 'foo bar baz'}
```

**Comment by jeremydw** [comment]
FYI, the "block-chomping character for trimming is `-'.

So, you'd update your YAML to:

```
multiline@: >-
  This is a multiline
  YAML string.
```

**Comment by WillsB3** [comment]
Ha - the chomping indicator looks exactly like what I want. Thanks for looking into this and that link. I also learned some more about YAML.

Let's close this out - I didn't realise YAML had so many different ways to specify a multi line string!
