### ISSUE TITLE
Improving build commands logging when an error occurs

### ISSUE THREAD

**Issue by WillsB3** [grow/pygrow#172]
When running `grow build` on a project where one of the pages does not build successfully it can be tricky to track down the problem, mostly because the build command doesn't identify which page/route it was building at the point when the error occurred.

Could we add some more helpful logging in the case of a build failure?

**Comment by jeremydw** [comment]
Thanks for filing this, I've needed it too. This is fixed in 9bf11b6521c13ffa4698590dd013dc76ae3b35f4 -- going to make a release tomorrow AM.
