### ISSUE TITLE
Relative url support for g.url()

### ISSUE THREAD

**Issue by WillsB3** [grow/pygrow#173]
Been thinking about this a little bit. We've come across situations where it would be nice if g.url could generate a relative URL for a document (from the current document). 

Is this something that has been considered before, and Is this something you think Grow should support and that you'd be open to exploring (via the medium of a pull request)?

**Comment by jeremydw** [comment]
Yes, think we should add this!

- Do middleman or jekyll support url generation in this way?
- What do you think would be a reasonable way to indicate that I want a relative URL instead of an absolute one?
- And, should we allow the user to generate relative URLs from documents other than the current, rendering document?

BTW – I think this should probably be part of the `Url` object (`doc.url`) – or if not part of, interface with it – and not the `g.url` tag, since the `g.url` tag is just a little shortcut for accessing the `url` property of a doc.

**Comment by jeremydw** [comment]
A cursory look shows Jekyll users use a macro:
http://ricostacruz.com/til/relative-paths-in-jekyll.html

And middleman has it built-in via the `relative` argument to `link_to`.
https://middlemanapp.com/basics/helper_methods/

**Comment by WillsB3** [comment]
My initial thought was to add an argument to g.url so that you could do something like:

```HTML+Django
<a href="{{g.url('/content/pages/index.html', relative=True).path}}">Home</a>
```

Do you think this is a reasonable interface?

I can't think of a use case where being able to generate a relative URL from a document other than the current document would be useful (but that doesn't mean that there isn't one...).

**Comment by jeremydw** [comment]
To make your snippet more maintainable (specifically, the link title), I'd suggest not using `g.url` and instead using `g.doc`. Example:

```
{% set link = g.doc('/content/pages/index.html') %}
<a href="{{link.url.relative_path}}">{{link.title}}</a>
```

The problem with the above is that `relative_path` wouldn't know what the current document/context is, unless we injected it into `g.doc`. We could do that, it might just get nasty. 

Another way to do it that's more explicit, though maybe needlessly verbose?

```
# Where "doc" is the current document.
{% set link = g.doc('/content/pages/index.html') %}
<a href="{{link.url.path_from(doc)}}">{{link.title}}</a>
```

Any more thoughts?

(Side note: Grow supports multiple document titles per page, so you could do the following for increased awesome maintainability.)

```
# In /content/pages/index.html
$title: Homepage
$titles:
  navbar: Home
$view: /views/base.html

# In /views/base.html
{% set link = g.doc('/content/pages/index.html') %}
<a href="{{link.url.relative_path}}">{{link.titles('navbar')}}</a>
```

**Comment by jeremydw** [comment]
Despite my previous hesitation, I actually don't think it'd be too bad to inject the current document automatically onto the `g.doc` template tag. That would enable you to simply do the following:

```
{% set home = g.doc('/content/pages/home.yaml') %}
<a href="{{home.url.relative_path}}">{{home.title}}</a>
```

It would also work with `g.url` to meet your example case:

```
{% set url = g.url('/content/pages/home.yaml') %}
{{url.relative_path}}
```

Think that'd be OK?
