### ISSUE TITLE
Gulp.js integration

### ISSUE THREAD

**Issue by mmccoy** [grow/pygrow#18]
I've used [Gulp.js](http://gulpjs.com/) on a few projects recently and find it to be an amazingly intuitive way of setting up a build workflow.  Just throwing a suggestion out there to integrate it into the 'grow build' command.

**Comment by jeremydw** [comment]
So I've also been using gulp with many Grow projects, and this is what I've standardized on.

In Gulp, I create a default task that watches for changes. When running Grow, I use: `gulp & grow run` – this starts Gulp and Grow at the same time, and using `Ctrl+C` quits both of them.

In Gulp, I also create a task named `build`. When building a site, I use `gulp build && grow build`, or when deploying `gulp build && grow deploy`. Gulp acts like a preprocessor, in this case.

This scheme works really well without any special integration between Gulp and Grow. I'm actually unsure if Gulp should control Grow or if Grow should control Gulp, so I think it may make sense to leave it as-is and up to the user? :) What do you think?

**Comment by mmccoy** [comment]
What is gulp giving you in those situations, what work is it doing?  

It seems to me that grow has (..wait for it) ...grown over the last year to do a lot of the same stuff I used to rely on gulp for.. (livereload, preprocessing, compilation/build, etc).  The plugin/module system gulp has is probably the main benefits its bringing to the table in a grow environment, right?  As for which should control which, I'd probably opt for just letting the user decide as you laid out above.

**Comment by jeremydw** [comment]
There are so many great processors available to Gulp, we wouldn't want to reinvent the wheel and have to rewrite them for Grow.

Here are a few things we've been using Gulp for:

* vulcanize (to compress Polymer dependencies into a single file)
* autoprefixer (magically applies vendor prefixes to CSS)
* Closure Compiler (there are issues executing Closure Compiler from Grow/Python that do not pop up when using Gulp)
* various other things like file concatenation, etc.

Gulp has been immensely awesome at the above (once working around a few one-time setup quirks).

Actually, I'd like to publish a Grow theme that includes a default gulpfile that leverages Closure Compiler, Angular externs, and autoprefixer. I've already published scaffold (https://github.com/growthemes/scaffold) but I'd like to rewrite it with a gulpfile.js. Maybe we can close this bug by updating scaffold with a gulpfile, and by writing some Gulp + Grow usage documentation on growsdk.org? I think documenting gulp as a first-party, but unintegrated, component might be a good approach. :)

**Comment by jeremydw** [comment]
Closing this out now since we have gulpfile examples already in the themes.
