### ISSUE TITLE
`pip install grow` fails with pip 6+

### ISSUE THREAD

**Issue by vitorio** [grow/pygrow#63]
Apparently sessions are a new thing in pip?

Just installed pip fresh on an OS X Yosemite system, got pip 6.0.8, did `pip install grow`, got:

    Collecting grow
      Downloading grow-0.0.40.tar.gz (6.1MB)
        100% |################################| 6.1MB 42kB/s 
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/private/var/folders/tp/tx8xhwrs4j969bmjjs_qww200000gn/T/pip-build-kguB0D/grow/setup.py", line 21, in <module>
            install_requires=[str(ir.req) for ir in _install_requirements],
          File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/pip-6.0.8-py2.7.egg/pip/req/req_file.py", line 19, in parse_requirements
            "parse_requirements() missing 1 required keyword argument: "
        TypeError: parse_requirements() missing 1 required keyword argument: 'session'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
        
          File "<string>", line 20, in <module>
        
          File "/private/var/folders/tp/tx8xhwrs4j969bmjjs_qww200000gn/T/pip-build-kguB0D/grow/setup.py", line 21, in <module>
        
            install_requires=[str(ir.req) for ir in _install_requirements],
        
          File "/Users/vitorio/Library/Python/2.7/lib/python/site-packages/pip-6.0.8-py2.7.egg/pip/req/req_file.py", line 19, in parse_requirements
        
            "parse_requirements() missing 1 required keyword argument: "
        
        TypeError: parse_requirements() missing 1 required keyword argument: 'session'
        
        ----------------------------------------
        Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tp/tx8xhwrs4j969bmjjs_qww200000gn/T/pip-build-kguB0D/grow

I think this is an example of another project with the same problem, and their fix: https://github.com/jmcarp/robobrowser/commit/89027e7eda38b1d7d244e161d659372b2de2b50b

**Comment by jeremydw** [comment]
Thanks for the report. I committed a fix to `develop`. I think you may be able to verify by installing using `pip` with the following command:

```
 pip install git+git://github.com/grow/pygrow.git@develop#egg=grow
```

**Comment by vitorio** [comment]
Hi!  Thanks!  It got further, but didn't quite finish:

    $ ~/Library/Python/2.7/bin/pip install --user git+git://github.com/grow/pygrow.git@develop#egg=grow
    Collecting grow from git+git://github.com/grow/pygrow.git@develop#egg=grow
      Cloning git://github.com/grow/pygrow.git (to develop) to /private/var/folders/tp/tx8xhwrs4j969bmjjs_qww200000gn/T/pip-build-hrFVVm/grow
    Collecting Babel==1.3 (from grow)
      Using cached Babel-1.3.tar.gz
    ...
    Collecting rednose==0.4.1 (from grow)
      Using cached rednose-0.4.1.tar.gz
    Collecting None (from grow)
      Could not find any downloads that satisfy the requirement None (from grow)
      Some externally hosted files were ignored as access to them may be unreliable (use --allow-external None to allow).
      No distributions at all found for None (from grow)

**Comment by jeremydw** [comment]
A rabbit hole. :) OK – let's give this another try. I removed PyInstaller (https://github.com/grow/pygrow/commit/3f5b99220830def581f14d09b324a8d675b49c31) which isn't really a requirement for the SDK (but rather, for contributors who freeze the code and build a binary).

I was able to reproduce your issue, and after removing the PyInstaller requirement, the issue went away. Give it a try now and let me know if you're able to install.

**Comment by vitorio** [comment]
It installed!  (I had to move Yosemite's system package of "six" out of the way to get an upgraded version to install in my userdir, but that's a Yosemite + --user issue, not specific to this.)

Running `grow` from my userdir Python bin (instead of the binary) also works.

Thanks!

**Comment by jeremydw** [comment]
That's great. Thanks for helping track this down!
