### ISSUE TITLE
Relative links in build and deploy files

### ISSUE THREAD

**Issue by Willis77** [grow/pygrow#70]
This may not be an error - I could just be missing something. When I **run** growsdk or codelab, all the links within the pages and sub-pages are fine. It appears that somehow within the server, all static items are always available at "/static/" regardless of path. When I generate the sites,however, with either build or deploy, the directory structure is not reflected in the links.

In codelab, for example, the static directory is referenced throughout in this way: 

```
href="/static/css/main.min.css"
```

But for the generated static site, what's really needed is the following.

At the root:

```
href="static/css/main.min.css"
```

From the pages:

```
href="../static/css/main.min.css"
```

And from the posts:

```
href="../../static/css/main.min.css"
```

Is this something that's supposed to be addressed through configuration? Or from manipulating the url from within the view?

A related problem seems to crop up if you set the root path. If you do so, you have to (logically) change where the static directory is served from in order to cause the build to place the static directory within the new root path directory. (404 page winds up outside, too, FWIW.) But changing where the static directory is served from does not change the generated links to:

```
href="/newrootpath/static/css/main.min.css"
```

They remain:

```
href="/static/css/main.min.css"
```

Again, this could be my ignorance. I'm still trying to figure it all out. But it is surprising in that the build & deploy results do not match those of the results of the built-in server.

**Comment by Willis77** [comment]
After looking at this a little more, I realize that it *was* my ignorance and not an error. If a built or generated site is placed at the root of the domain, there's no issue. I was testing in a subdirectory of a local server, and hence my problems.

I wonder, though, if there could be an option to build with relative URLs. Or, even better, a variable that contains the path of the static directory. I initially misunderstood g.static(), thinking it would provide this functionality - that I could call `g.static('/static/images/icon.png')`, for example, and it would automatically return `'/static/images/icon.png'`, or `'/growtest/static/images/icon.png'`, or whatever, depending upon where the static directory was being served from.

If such a variable existed, the next question I'd have is: any chance of ever using variables within the markdown itself, rather than just the front matter? I don't know what would be involved in creating that functionality, but it would make Grow (even more) incredibly flexible.

**Comment by jeremydw** [comment]
Hey there – I just wanted to give you a little update on the subject of this issue (paths to static files defined by `static_dirs`). In *0.0.51* we implemented `g.static` (before it was unimplemented). See the release notes here: https://github.com/grow/pygrow/releases/tag/0.0.51 and the documentation here: http://growsdk.org/docs/templates/#gstatic

Here's example usage:

```
# In podspec.yaml
static_dirs:
- static_dir: /source/images/
  serve_at: /static/images/
```

```
# In /views/base.html
<img src="{{g.static('/source/images/file.png')}}">

# Results in
<img src="/static/images/file.png">
```

Basically, `g.static` returns a StaticFile object when given the pod path (the internal path) of a static file in a `static_dirs` directory. From that StaticFile object, you can access the `url.path` property to resolve the file's serving path. This is particularly useful as it allows you to change a file's URL path without moving the file internally – and it also helps avoid broken links as the tag raises an error if it cannot find the file locally.

One note – `url.path` always returns the absolute path of the file's serving path.

While the `url.path` property is the only property implemented right now, in the future we can expand the available properties to add more features – such as a theoretical `url.relative_path` that would presumably return the relative path of the StaticFile based on the current document that's wondering.

Anyway, does the current implementation of `g.static` meet your needs? If not, what else would you find useful? Thanks!

**Comment by jeremydw** [comment]
We're planning to implement relative links alongside absolute links – as an option, should folks want them. Tracking the development of that in #173
