### ISSUE TITLE
How to define partial content collections?

### ISSUE THREAD

**Issue by vitorio** [grow/pygrow#82]
The documentation says:

> Content documents can be associated with URLs and with views (so they represent pages in your site), or not. Content documents without URLs are simply used internally, and can be referenced by other content documents.

and

> If path is omitted, content in this collection will not be generated into pages. If path is specified, view is a required field.

Which I interpret to mean, if I do not define paths, by having an empty `_blueprint.yaml` file in my collection directory, then the `filename.html` HTML snippet content in it (which also has no YAML front matter) will not have paths generated for it, but will be able to be referenced by other content by specifying a document path as a variable and referencing it in my template like this:

```
{% set fbpixel = g.doc(doc.fbpixel) %}
{{fbpixel.html|safe}}
```

However, this does not appear to be the case.  An empty `_blueprint.yaml`, with no `path` or `view` specified, still causes the documents to try to be processed in `collectionz.py` `list_documents()` `process()`.  Providing YAML front matter to define `$hidden: true` also does not help, as it continues onto the locale handling code.

It seems the minimum amount of YAML for this to work as expected is a `_blueprint.yaml` with only:

```
path: 
```

**And also** the same in the front matter for my HTML snippet.  Only having one or the other does not seem to work: only in the front matter and there's a locale issue; only in the blueprint and there's a path naming issue.

(Also, when debugging this, the routing table seems to not clear itself properly; I kept having to kill and re-run `grow run` to triage this.)

So:

1. Am I including one piece of content in another properly?
2. Is this the intended behavior of a partial piece of content without a rendered URL or path?

(I expected an empty `_blueprint.yaml` and needing no front matter to work.)

**Comment by vitorio** [comment]
Oh, alternately, an empty `_blueprint.yaml`, and content filenames that all start with underscores, seems to work.

**Comment by jeremydw** [comment]
Recently I added code in both https://github.com/grow/pygrow/commit/269befd364acbfbb6fd4d68050438c86c2b7e0b8 and https://github.com/grow/pygrow/commit/c1d9325f0739624ac8cf482d9ed838debd6e26de that adds and verifies the ability to have empty `_blueprint.yaml` files and also documents with empty front matter (documentation to be updated shortly). This means that you'll be able to use `g.doc` and `g.docs` against these documents and collections.

In addition to using `g.docs` or `g.doc` with these content documents and collections, if you wanted to leverage partial content collections, or partial content, or even just arbitrary YAML files that might not pertain to a specific collection, you could also use the [g.yaml tag](http://growsdk.org/docs/templates/#gyaml) with a YAML file in your pod.

If you have an arbitrary YAML file in `/data/file.yaml`, you could use:

```
{% set data = g.yaml('/data/file.yaml') %}
```

and then access `{{data}}` as you might expect.

**Comment by jeremydw** [comment]
Haven't heard anything on this comment in a while, so closing for now. Please re-open if you'd like to continue the discussion and/or if the looser restrictions on documents and collections and the `g.yaml` tag aren't sufficient for you!

**Comment by vitorio** [comment]
Hi!  Sorry for disappearing after the fixes were made.  Yes, the changes did work out for me, although I recently ran into a related issue, but I'll open a new ticket for that.  Thanks!
