### ISSUE TITLE
YAML front matter doesn't appear to be optional for HTML content documents

### ISSUE THREAD

**Issue by vitorio** [grow/pygrow#83]
From the documentation:

> As long as a blueprint specifies a document's view and its path, including YAML front matter in a content document is optional.

I have a `_blueprint.yaml` that contains:

```
path: /{base}               # The URL path format.
view: /views/studies.html      # The template to use.
title: Studies                 # Collection's title.
```

and a `filename.html` content item in the same folder.  Without at least:

```
---
path: 
---
```

as the YAML front matter, `grow run` errors out with `'str' object has no attribute 'get'`, which is the same naming issue I was seeing in #82.

This does not happen with Markdown content documents using the same blueprint, those work fine.

**Comment by jeremydw** [comment]
Thanks for the report – in fact, I noticed the between the documentation and reality the other day. The commit with an initial fix is 269befd. About to push up a commit that fixes the "no front matter" issue for HTML-formatted documents as well.
