### ISSUE TITLE
Improve ability to specify document's default locale

### ISSUE THREAD

**Issue by meizon** [grow/pygrow#92]
Example: We have a page that is available in certain locales but *not* the base, so it would be useful to be able to turn it off so the base locale page isn't generated.

**Comment by jeremydw** [comment]
45c2494 has added the ability for documents to properly specify their `default_locale` such that when `{{doc.locale}}` is access, the correct `default_locale` for that document is used.

This also permits the ability to use the `{locale}` placeholder in a document's path – with the `default_locale` correctly substituted (with support for aliases such as `en_uk: en_gb`).

Relevant examples:
- https://github.com/grow/pygrow/blob/feature/default-locale/grow/testing/testdata/pod/content/pages/contact.yaml#L1
- https://github.com/grow/pygrow/blob/feature/default-locale/grow/pods/collectionz/documents_test.py#L46

Also filed an issue to research and add support for custom locales: https://github.com/grow/pygrow/issues/93

**Comment by meizon** [comment]
This is great. Good work Jeremy.

**Comment by jeremydw** [comment]
Thanks – going to close this one out. We'll do a new release after solving #93.

If you get a chance, feel free to build from source and try out this feature. That said – I've already confirmed it works on our project for the GB pages – including using `{locale}` in the base path and having the base page use the correct `en_GB` locale. :)
